router:
  name: "ConfigLLMRouter"
  version: "1.0"

  runtime:
    trace_enabled: true
    metrics_enabled: true
    timeout_ms: 2000

  gate:
    modality_detection:
      allow_llm: true
      infer_keys: ["has_url","has_file","has_image","has_voice","has_video","has_text"]
      map_files_by_media_type: true
    family_selection:
      policy_allowlist:
        allow: ["core","media","images","video","ocr","qr","table","schedule","network","finance","music"]
        deny: []
      resource_gate:
        enforce_modal_requirements: true
        min_overlap: 0.15
    soft_cues_to_prior:
      enabled: true
      decay: 0.30

  thresholds:
    domain_lock_margin: 0.18
    tau_exec: 0.62
    tau_clarify: 0.42
    tau_fallback: 0.20

  models:
    dense_sr:
      embedder: ""
      index_uri: ""
      normalize: true
      topK_sem: 30
      min_score: 0.05
    llm_recall:
      model: ""
      temperature: 0.1
      max_tokens: 256
      topK_llm: 12
      prompt_template_ref: "recall_v1"
    memory_summarizer:
      model: ""
      temperature: 0.1
      max_tokens: 256
    cross_encoder:
      enabled: true
      model: ""
      max_pairs: 12
    calibrator:
      method: "isotonic"
      table_uri: ""

  ranker:
    candidate_generation:
      dense_sr:
        enabled: true
        topK: 30
        family_filter: "soft"
      llm_recall:
        enabled: true
        allowed_families: []
        use_memory_context: true
        topK: 12
        prompt_template_ref: "recall_v1"
        include_rationales: true
    fusion:
      method: "weighted_rrf"
      weights:
        dense_sr: 0.6
        llm_prior: 0.4
      shortlist_topN: 12
    precision_rerank:
      enabled: true
      cross_encoder:
        enabled: true
        max_pairs: 12
      features:
        include: ["sr_score","ce_score","slot_readiness_llm","resource_match","session_affinity","memory_consistency","topic_shift","safety_hint"]
      ltr_blend:
        method: "logistic"
        model_uri: ""
      calibration:
        method: "isotonic"
        table_uri: ""

  merge_prepare:
    sticky_bind:
      prefer_last_file_for_families: ["media","images","video","ocr","qr","table","music"]
      prefer_last_url_for_families: ["media","video","core"]
      guard_user_negation_phrases:
        - "not that"
        - "use a different file"
        - "different link"
        - "نه همون"
    auto_fill_trivial_pairs:
      rules:
        - name: "date_plus_time_to_datetime"
          when_present: ["date","time"]
          produce: "datetime"
        - name: "file_or_url_prefer_file"
          when_present: ["file_id","url"]
          produce: "source"
          precedence: ["file_id","url"]
    canonicalize:
      datetime_to_iso_8601: true
      timezone: "session"

  policy:
    provider_allowlist:
      stt: ["whisper","deepgram"]
      translate: ["gpt"]
      ocr: ["tesseract"]
    caps:
      stt: { max_duration_s: 1800 }
      media: { max_bytes: 500000000 }
      vision: { max_pixels: 268435456 }
    safe_fallbacks:
      when_external_scrape_denied: "inline_tldr"
      when_video_too_long: "chapters_only"
    pre_clarify:
      enabled: true
      ask_at_most: 1
      friendly_labels_ref: "clarify_prompts"
      triggers:
        - reason: "missing_critical_single"
          if_missing_keys_one_of: ["start","end","at","recipient","playlist_id","booking_ref"]
        - reason: "ambiguous_source"
          if_conflict: ["file_id","url"]
        - reason: "provider_cap_exceeded"
          when_cap_hit: true

  finalize:
    plan_skeleton:
      max_tasks: 3
      include_top_intent_only: true
      attach_llm_cues_as_nonbinding: true
      include_missing_keys_summary: true
    clarify_fallback:
      when_below_tau_clarify: true
      message_style_by_locale:
        en-US: { tone: "friendly", register: "neutral" }
        fa-IR: { tone: "formal", register: "polite" }
    graceful_fallback:
      below_tau_fallback_to: "chat.general"
      text_when_fallback:
        en-US: "I can help with that—could you say it another way?"
        fa-IR: "می‌تونم کمک کنم—ممکنه کمی واضح‌تر توضیح بدید؟"

  prompts:
    recall_v1:
      system: |
        You are an intent recall assistant. Return top candidate intents by name only,
        with brief rationales. Do not extract fields/slots.
      user_template: |
        Message:
        - text: {text}
        - urls: {urls}
        - attachments: {attachments}
        - locale: {locale}, tz: {timezone}
        Session snapshot:
        - last_url: {last_url}
        - last_file: {last_file}
        - last_intent_hint: {last_intent_hint}
        Families gated: {families}
        List up to {topK} intents.
      output_schema_hint: "List[{intent: string, rationale: string}]"
    clarify_prompts:
      en-US:
        missing_single: "Please provide **{field}**."
        ambiguous_source: "Should I use the last file or the link you mentioned?"
      fa-IR:
        missing_single: "لطفاً **{field}** را مشخص کنید."
        ambiguous_source: "از فایل قبلی استفاده کنم یا لینکی که گفتید؟"

  expansions:
    image.generate:
      - intent: "image.generate"
    image.describe:
      - intent: "image.describe"
    image.remove_bg:
      - intent: "image.remove_bg"
    qr.decode:
      - intent: "qr.decode"
    barcode.decode:
      - intent: "barcode.decode"
    text.summarize:
      - intent: "text.summarize"
    text.translate:
      - intent: "text.translate"
    tts.speak:
      - intent: "tts.speak"
    network.vpn.get:
      - intent: "network.vpn.get"
    finance.crypto.price:
      - intent: "finance.crypto.price"
    finance.crypto.ohlc:
      - intent: "finance.crypto.ohlc"
    finance.fx.rate:
      - intent: "finance.fx.rate"
    finance.fx.convert:
      - intent: "finance.fx.convert"
    sched.availability.show:
      - intent: "sched.availability.show"
    sched.book:
      - intent: "sched.book"
    sched.reschedule:
      - intent: "sched.reschedule"
    sched.cancel:
      - intent: "sched.cancel"
    tutor.chat.correct:
      - intent: "tutor.chat.correct"
    music.convert:
      - intent: "music.convert"
    music.preview:
      - intent: "music.preview"
    music.normalize:
      - intent: "music.normalize"
    media.chapters:
      - intent: "media.ingest_url"
      - intent: "media.transcript"
      - intent: "media.chapters"
    media.quotes:
      - intent: "media.ingest_url"
      - intent: "media.transcript"
      - intent: "media.quotes"
    media.translate_only:
      - intent: "media.ingest_url"
      - intent: "media.transcript"
      - intent: "text.translate"
    video.thumbnail:
      - intent: "video.thumbnail"
    video.gif:
      - intent: "video.gif"
    "ocr+summary":
      - intent: "ocr.extract"
      - intent: "ocr.tldr"

  slotfill:
    enabled: true
    model: "gpt-5-nano"
    max_calls_per_turn: 2
    routes:
      music.playlist.remove:
        fields:
          track_id:
            type: "id"
            patterns: ['\bTRK-\d+\b']
            required: true
          playlist_id:
            type: "id"
            patterns: ['\bPLAY-\d+\b']
            required: true
          playlist_name:
            type: "name"
            patterns: ['"([^"]+)"', 'playlist\s+([A-Za-z0-9][\w\s\-]+)']
            required: false
        allow_names_for_ids: ["playlist_id->playlist_name"]

      sched.book:
        fields:
          datetime: { type: "datetime" }
          date: { type: "date" }
          time: { type: "time" }
          attendee: { type: "person|email|phone" }

      music.send:
        fields:
          recipient:
            type: "email|phone|handle"
            patterns:
              - '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}'
              - '\+?\d[\d\-\s]{6,}\d'
              - '@\w+'

      sched.reschedule:
        fields:
          booking_ref:
            type: "id"
            patterns: ['(?:booking|ref(?:erence)?|code|کد)\s*[:\-#]?\s*([A-Za-z0-9_\-]+)']
            required: true
          datetime: { type: "datetime" }
          date: { type: "date|date_fuzzy" }
          time: { type: "time|time_ampm" }

      network.proxy.get:
        fields:
          region:
            type: "name"
            patterns:
              - '\b(US|USA|United\s*States|UK|United\s*Kingdom|DE|Germany|NL|Netherlands|EU|Europe)\b'
              - '(آمریکا|بریتانیا|انگلیس|آلمان|هلند|اروپا)'
          purpose:
            type: "name"
            patterns:
              - '\b(stream(?:ing)?|netflix|gaming|privacy|secure|torrent|scrap(?:e|ing))\b'
              - '(استریم|نتفلیکس|بازی|حریم\s*خصوصی|امنیت|کراول|اسکیریپ)'
            required: false

      music.inline.search:
        fields:
          query:
            type: "name"
            patterns:
              - '(?:songs?|tracks?|music)\s+(?:by|from)\s+([^\n,.]+)'
              - 'artist\s*:\s*([^\n]+)'
            required: true

      music.playlist.add:
        fields:
          track_id:
            type: "id"
            patterns: ['\bTRK-\d+\b']
            required: true
          playlist_id:
            type: "id"
            patterns: ['\bPLAY-\d+\b']
            required: false
          playlist_name:
            type: "name"
            patterns: ['"([^"]+)"', 'playlist\s+([A-Za-z0-9][\w\s\-]+)']
            required: false
        allow_names_for_ids: ["playlist_id->playlist_name"]

      music.cover.attach:
        fields:
          track_id:
            type: "id"
            patterns: ['\bTRK-\d+\b']
            required: true

      video.thumbnail:
        fields:
          at:
            type: "time|time_hhmmss|time_ampm"
            patterns: ['\b(\d{1,2}:\d{2}(?::\d{2})?)\b', '\b(\d{1,3})s\b']
            required: true

      video.gif:
        fields:
          start:
            type: "time|time_hhmmss"
            patterns: ['(\d{1,2}:\d{2}(?::\d{2})?|\d{1,3}s)']
          end:
            type: "time|time_hhmmss"
            patterns: ['(\d{1,2}:\d{2}(?::\d{2})?|\d{1,3}s)']

      qr.generate:
        fields:
          text: { type: "quoted_name|name" }
          url:
            type: "url"
            patterns: ['https?://\S+']

      finance.fx.convert:
        fields:
          amount:
            type: "amount"
            patterns: ['\b(\d+(?:\.\d+)?)\b']
            required: true
          from_currency:
            type: "id"
            patterns: ['\b([A-Z]{3})\b']
            required: true
          to_currency:
            type: "id"
            patterns: ['\b([A-Z]{3})\b']
            required: true
          date: { type: "date|date_fuzzy" }

      finance.crypto.ticker:
        fields:
          from:
            type: "id"
            patterns: ['\b([A-Za-z]{2,6})(?=/[A-Za-z]{2,6}\b)']
          to:
            type: "id"
            patterns: ['(?<=\b[A-Za-z]{2,6}/)([A-Za-z]{2,6})\b']
          from_concat:
            type: "id"
            patterns: ['\b([A-Za-z]{2,6})(?=USDT\b|USD\b|EUR\b|BTC\b|ETH\b)']
          to_concat:
            type: "id"
            patterns: ['\b(USDT|USD|EUR|BTC|ETH)\b']
        ask_user_templates:
          from: "Base asset? (e.g., BTC)"
          to: "Quote asset? (e.g., USDT)"

    defaults:
      email: '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}'
      phone: '\+?\d[\d\-\s]{6,}\d'
      quoted_name: "['\"“”«»]([^'\"“”«»]+)['\"“”«»]"
      datetime: '\b\d{4}-\d{2}-\d{2}\s+\d{1,2}:\d{2}\b'
      date: '\b\d{4}-\d{2}-\d{2}\b'
      time: '\b\d{1,2}:\d{2}\b'
      time_ampm: '\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)\b'
      time_hhmmss: '\b\d{1,2}:\d{2}:\d{2}\b'
      date_fuzzy: '\b(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)?\.?\,?\s*(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{1,2}\b'
      url: 'https?://\S+'
      amount: '\b\d+(?:\.\d+)?\b'
